service: nft-handlers

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    PANCAKE_BUNNY_ADDRESS: 'your-pancake-bunny-address'
    MONGO_URI: 'mongodb+srv://higor:956tD44DkIfdh2u2@cluster0.4igvt9x.mongodb.net/publish-nft-db?retryWrites=true&w=majority'

functions:
  getAttributesDistribution:
    handler: src/handlers/getDistributions.handler
    timeout: 10
    events:
      - http:
          path: /attributes/distribution
          method: get
          cors: true
  getCollection:
    handler: src/handlers/getCollections.handler
    timeout: 10
    events:
      - http:
          path: /collections
          method: get
          cors: true
  getCollectionByAddress:
    handler: src/handlers/getCollectionsByAddress.handler
    timeout: 10
    events:
      - http:
          path: /collection/{address}
          method: get
          cors: true
  getTokensByAddressAndId:
    handler: src/handlers/tokens/getTokensByAddressAndId.handler
    timeout: 10
    events:
      - http:
          path: tokens/{address}/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                address: true
                id: true
  getTokensFiltered:
    handler: src/handlers/tokens/getTokensFiltered.handler
    timeout: 10
    events:
      - http:
          path: tokens/filtered/{address}
          method: get
          cors: true
          request:
            parameters:
              paths:
                address: true
              querystrings:
                page: false
                size: false
  getTokens:
    handler: src/handlers/tokens/getTokens.handler
    timeout: 10
    events:
      - http:
          path: /tokens
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline